spring.application.name=proyecto-spring
spring.thymeleaf.cache=false

#conexion con neon
# URL de conexi�n (Notar�s que agregamos "jdbc:" al principio)
spring.datasource.url=jdbc:postgresql://ep-wandering-cell-ape668pn-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

# Credenciales extra�das de tu cadena
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jhY4duGM0HkE

# Configuraci�n del Driver y JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Control de creaci�n de tablas (usa 'update' para desarrollo y 'validate' para producci�n)
# none: la BD ya existe con el script SQL; no alterar ni validar tipos estrictos
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=false