spring.application.name=proyecto-spring
spring.thymeleaf.cache=false

# ---- H2 + Hibernate ddl-auto ----
# Dejamos que Hibernate cree/actualice el esquema en base al modelado @Entity.
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update






spring.datasource.url=jdbc:h2:mem:proyecto-spring;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


