-- Base de datos H2 (solo ejemplo de schema mínimo)
-- Paso 1: crear tabla para un modelo (HistoriaClinica) y relación 1:1 con Anamnesis.

CREATE TABLE IF NOT EXISTS paciente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  apellido VARCHAR(120) NOT NULL,
  dni VARCHAR(20) UNIQUE,
  celular VARCHAR(30),
  correo VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS historia_clinica (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id BIGINT NOT NULL,
  motivo_consulta VARCHAR(255),
  observaciones VARCHAR(1000),
  CONSTRAINT fk_historia_paciente FOREIGN KEY (paciente_id) REFERENCES paciente(id)
);

CREATE TABLE IF NOT EXISTS anamnesis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  historia_clinica_id BIGINT NOT NULL UNIQUE,
  fecha DATE,
  historia_familiar VARCHAR(2000),
  historia_personal VARCHAR(2000),
  antecedentes_escolares VARCHAR(2000),
  antecedentes_medicos VARCHAR(2000),
  antecedentes_psiquiatricos VARCHAR(2000),
  sintomas_principales VARCHAR(2000),
  comentarios VARCHAR(2000),
  CONSTRAINT fk_anamnesis_historia FOREIGN KEY (historia_clinica_id) REFERENCES historia_clinica(id)
);

